# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2e0d4096fb1c73f0851cb3bfb9e92210"
name = "POS Sync"
application_url = "https://renewal-dining-america-additionally.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

[access_scopes]
scopes = "read_inventory,read_product_listings,read_products,write_inventory,write_product_listings,write_products"

[auth]
redirect_urls = [
  "https://renewal-dining-america-additionally.trycloudflare.com/auth/callback",
  "https://renewal-dining-america-additionally.trycloudflare.com/auth/shopify/callback"
]
