# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2e0d4096fb1c73f0851cb3bfb9e92210"
name = "POS Sync"
application_url = "https://pos-sync-shopify.tarawud.com"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_product_listings,read_products,write_inventory,write_product_listings,write_products"

[auth]
redirect_urls = [
  "https://pos-sync-shopify.tarawud.com/auth/callback",
  "https://pos-sync-shopify.tarawud.com/auth/shopify/callback"
]
